In [74]:
import numpy as np

r,c=map(int,input().split())
sy,sx=map(int,input().split())
gy,gx=map(int,input().split())

7 8
2 2
4 5


In [99]:
py=sy-1;px=sx-1
d=np.array([],dtype=int)

In [100]:
for i in range(r):
    di=list(map(lambda x:(x=='.')+0,list(input())))
    print(di)
    d=np.append(d,di)

########
[0, 0, 0, 0, 0, 0, 0, 0]
#......#
[0, 1, 1, 1, 1, 1, 1, 0]
#.######
[0, 1, 0, 0, 0, 0, 0, 0]
#..#...#
[0, 1, 1, 0, 1, 1, 1, 0]
#..##..#
[0, 1, 1, 0, 0, 1, 1, 0]
##.....#
[0, 0, 1, 1, 1, 1, 1, 0]
########
[0, 0, 0, 0, 0, 0, 0, 0]


In [101]:
len(d)

56

In [102]:
d2=np.reshape(d,[r,c])

In [103]:
np.reshape(d,[r,c])

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [104]:
d2[py-1,px]=(d2[py,px]+1)*d2[py-1,px]
d2[py,px-1]=(d2[py,px]+1)*d2[py,px-1]
d2[py,px+1]=(d2[py,px]+1)*d2[py,px+1]
d2[py+1,px]=(d2[py,px]+1)*d2[py+1,px]

In [105]:
d2

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 1, 1, 1, 1, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [119]:
pypx=np.where(d2 == 2)
len(pypx)

2

In [118]:
pypx[0]

array([1, 2], dtype=int64)