In [2]:
n=int(input())
a=list(map(int,input().split()))
b=list(map(int,input().split()))

3
17 7 1
25 6 14


In [3]:
if sum(a)>=sum(b):
    print(n)

else:
    print(-1)

-1


In [7]:
import numpy as np
a=np.array(a)

In [8]:
a

array([2, 3, 5])

In [9]:
b=np.array(b)

In [10]:
b

array([3, 4, 1])

In [16]:
sabun=a-b

In [19]:
husoku = sabun[sabun < 0]

In [20]:
husoku

array([-1, -1])

In [21]:
yojyo = sabun[sabun > 0]

In [22]:
yojyo

array([4])

In [1]:
import numpy as np
n=int(input())
a=list(map(int,input().split()))
b=list(map(int,input().split()))

if sum(a)>=sum(b):
    a=np.array(a)
    b=np.array(b)
    sabun=a-b
    husoku = sabun[sabun < 0]
    yojyo = sabun[sabun > 0]
    for i in range(len(yojyo)):
        if -1*sum(husoku)<sum(yojyo[0:i+1]):
            print(i+1+len(husoku))
            exit()

else:
    print(-1)


3
17 7 1
25 6 14
-1


In [27]:
-1*sum(husoku)

2

# 解説を読んでから実装

In [2]:
n=int(input())
a=list(map(int,input().split()))
b=list(map(int,input().split()))

s1=[]
s2=[]
for i in range(n):
    if a[i]>=b[i]:
        s1.append(a[i]-b[i])
    else:
        s2.append(b[i]-a[i])


if sum(a)>=sum(b):
    for i in range(len(s1)+1):
        if sum(sorted(s1, reverse=True)[0:i])>=sum(s2):
            print(i+len(s2))
#             exit()
else:
    print(-1)

12
757232153 372327760 440075441 195848680 354974235 458054863 463477172 740174259 615762794 632963102 529866931 64991604
74164189 98239366 465611891 362739947 147060907 118867039 63189252 78303147 501410831 110823640 122948912 572905212
5
6
7
8
9
10
11
12


In [20]:
s1

[1]

In [21]:
s2

[8, 13]

In [3]:
n

12

In [4]:
a

[757232153,
 372327760,
 440075441,
 195848680,
 354974235,
 458054863,
 463477172,
 740174259,
 615762794,
 632963102,
 529866931,
 64991604]

In [5]:
b

[74164189,
 98239366,
 465611891,
 362739947,
 147060907,
 118867039,
 63189252,
 78303147,
 501410831,
 110823640,
 122948912,
 572905212]

In [9]:
list(map(lambda x,y: x-y, a-b))

TypeError: unsupported operand type(s) for -: 'list' and 'list'