In [16]:
import numpy as np

L, N = map(int, input().split())

Xlist = []
for i in range(N):
    Xlist.append(int(input()))
Xlist = np.array(Xlist)

def distance_fromX(x, a, l) :
    dist1 = []
    dist2 = []
    for i in range(len(x)):
        dist1.append(x[i] - a)
        dist2.append(l - x[i] - a)
    return([[min(dist1),min(dist2)], [dist1.index(min(dist1)),dist2.index(min(dist2))]])

def fire_index(x):
    return([max(x[0]),x[1][x[0].index(max(x[0]))]])

dist = 0
a = 0
for i in range(0,N):
    dfx = distance_fromX(Xlist,a, L)
    print(dfx)
    fi = fire_index(dfx)
    dist = dist + max(dfx[0])
    
    ind = np.ones(N-i, dtype=bool)
    ind[fi[1]] = False
    a = Xlist[fi[1]]
    Xlist = np.array(Xlist)[ind]
    
#     print([a,max(dfx[0])])
    print(Xlist)
#     print(max(dfx[0]))
print(dist)

10 6
1
2
3
6
7
8
[[1, 2], [0, 5]]
[1 2 3 6 7]
[[-7, -5], [0, 4]]
[1 2 3 6]
[[-6, -3], [0, 3]]
[1 2 3]
[[-5, 1], [0, 2]]
[1 2]
[[-2, 5], [0, 1]]
[1]
[[-1, 7], [0, 0]]
[]
7


In [70]:
distance_fromX([7,9],2, 10)

[[5, 3], [0, 1]]

In [86]:
i

0

In [2]:
Xlist

array([], dtype=int32)

In [4]:
Xlist_t = [1,2,3,6,7,9]

In [5]:
L

10

In [6]:
N

6

In [40]:
a = 8

In [41]:
dist1_t = []
dist2_t = []
for i in Xlist_t:
    dist1_t.append(i - a)
    dist2_t.append(L - (i - a))
print([dist1_t[0], dist2_t[-1]])

[-7, 9]


In [42]:
dist1_t

[-7, -6, -5, -2, -1, 1]

In [43]:
dist2_t

[17, 16, 15, 12, 11, 9]

In [52]:
[min(abs(np.array(Xlist_t)-8))]

[1]

In [60]:

idx = list(abs(np.array(Xlist_t)-a)).index(min(abs(np.array(Xlist_t)-a)))

4

In [67]:
Xlist_t = [1,2,3,6,7,9]
L = 10
N = 6

a = 0
dist = 0
for i in range(N):

    idx = list(abs(np.array(Xlist_t)-a)).index(min(abs(np.array(Xlist_t)-a)))
    dist = dist + max(abs(np.array(Xlist_t)-a))
    a = Xlist_t[idx]
    ind = np.ones(N-i, dtype=bool)
    ind[idx] = False
    Xlist_t = np.array(Xlist_t)[ind]
    print(dist)
    
print(dist)

9
17
24
30
33
35
35
