In [ ]:
int(input())

In [ ]:
map(int, input().split())

In [ ]:
N, i = map(int, input().split())
print(N-i+1)

In [105]:
import numpy as np
H, W = map(int, input().split())
a_list = []
for i in range(H):
    a_list.append(list(map(str, input().split())))
dot = '....................................................................................................'

a_list2 = []
for i in range(H):
    if a_list[i] != [dot[0:W]]:
        a_list2.append([c for c in a_list[i][0]])

a_list3 = []
for i in range(len(a_list2[0])):
    if ''.join(list(np.array(a_list2)[:,i])) != dot[0:len(a_list2)]:
        a_list3.append(list(np.array(a_list2)[:,i]))

for i in range(len(a_list3[0])):
    print(''.join(list(np.array(a_list3).T[i,:])))

7 6
......
....#.
.#....
..#...
..#...
......
.#..#.
..#
#..
.#.
.#.
#.#


In [103]:
a_list2 = []
for i in range(H):
    if a_list[i] != [dot[0:W]]:
        a_list2.append([c for c in a_list[i][0]])

In [99]:
a_list

[['.....'], ['.....'], ['..#..'], ['.....']]

In [100]:
[dot[0:W]]

['.....']

In [101]:
W

5

In [102]:
for i in range(W):
    print(a_list[i])

['.....']
['.....']
['..#..']
['.....']


IndexError: list index out of range

In [188]:
N, K = map(int, input().split())
x_list = list(map(int, input().split()))

5 3
-30 -10 10 20 50


In [192]:
N, K = map(int, input().split())
x_list = list(map(int, input().split()))
mainasu = []
purasu = []
p = 0
for i in range(N):
    if x_list[i] > p:
        purasu.append(x_list[i])
    else:
        mainasu.append(x_list[i])
        


In [114]:
p = 0
x_list

array([30, 10, 10, 20, 50])

In [119]:
N = int(input())
an_list = list(map(int, input().split()))

3
10 30 20


In [120]:
an_list

[10, 30, 20]

In [186]:
import statistics
import math
import numpy as np

N = int(input())
an_list = list(map(int, input().split()))
med_list = np.arange(0)

for i in range(0,N+1):
    for j in range(i+1,N+1):
        if i != j :
            med_list = np.append(med_list, [statistics.median_high(np.array(an_list)[i:j])])
#             print(an_list[i:j])

print(statistics.median_high(med_list))

10
5 9 5 9 8 9 3 5 4 3
8


In [177]:
an_list[i:j]
print([i,j])

[10, 10]


In [180]:
np.array(an_list)[1:9]

array([9, 5, 9, 8, 9, 3, 5, 4])

In [185]:
med_list

array([], dtype=int32)

In [170]:
m = np.arange(0)
np.append(m,statistics.median_high(np.array(an_list)))

array([5])

In [163]:
med_list

[5,
 9,
 5,
 9,
 8,
 9,
 8,
 8,
 5,
 5,
 9,
 9,
 9,
 9,
 9,
 9,
 8,
 8,
 5,
 5,
 9,
 8,
 9,
 8,
 8,
 5,
 5,
 9,
 9,
 9,
 9,
 8,
 8,
 5,
 8,
 9,
 8,
 8,
 5,
 5,
 9,
 9,
 5,
 5,
 4,
 3,
 5,
 4,
 4,
 5,
 5,
 4,
 4,
 4,
 3]