In [1]:
9*12

108

In [2]:
91*34

3094

In [72]:
N, M, A, B = list(map(int, input().split()))

mikan = [B] * N
A = [A] * N
for i in range(M):
    LR = list(map(int, input().split()))
    mikan[(LR[0] - 1):(LR[1])] = A[(LR[0] - 1):(LR[1])]
print(int(sum(mikan)))

5 2 6 7
2 3
3 4
32


In [71]:
mikan[(LR[0] - 1):(LR[1])]

[7, 7]

In [63]:
np.ones(N) * B

array([ 7.,  7.,  7.,  7.,  7.])

In [60]:
[B] * N

[7, 7, 7, 7, 7]

In [55]:
LR[0]

3

In [57]:
mikan[range((np.array(LR) - 1)[0],(np.array(LR) - 1)[1] + 1)]

array([ 6.,  6.])

In [58]:
mikan[range(LR[0] - 1, LR[1])]

array([ 6.,  6.])

In [39]:
mikan[np.array(LR[i]) - 1]

array([ 20.,  20.])

In [45]:
mikan[range((np.array(LR[M]) - 1)[0],(np.array(LR[M]) - 1)[1])]

array([ 20.,  20.,  20.,  30.,  30.])

In [28]:
mikan

array([ 30.,  20.,  20.,  30.,  30.,  30.,  20.,  20.,  30.,  30.])