In [25]:
import numpy as np

In [26]:
mat = np.zeros(36,dtype=int).reshape(6,6)

In [27]:
mat[1,2] = 1
mat[0,1] = 1
mat[4,5] = 1
mat[2,3] = 1
mat[3,4] = 1

mat[2,1] = 1
mat[1,0] = 1
mat[5,4] = 1
mat[3,2] = 1
mat[4,3] = 1

In [34]:
mat1 = np.dot(mat,mat)
mat1

array([[1, 0, 1, 0, 0, 0],
       [0, 2, 0, 1, 0, 0],
       [1, 0, 2, 0, 1, 0],
       [0, 1, 0, 2, 0, 1],
       [0, 0, 1, 0, 2, 0],
       [0, 0, 0, 1, 0, 1]])

In [35]:
np.diag(mat1)

array([1, 2, 2, 2, 2, 1])

In [36]:
mat[1,2] = 0
mat[0,1] = 1
mat[4,5] = 1
mat[2,3] = 1
mat[3,4] = 1

mat[2,1] = 0
mat[1,0] = 1
mat[5,4] = 1
mat[3,2] = 1
mat[4,3] = 1

In [39]:
mat2 = np.dot(mat,mat)
mat2

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 0, 2, 0, 1],
       [0, 0, 1, 0, 2, 0],
       [0, 0, 0, 1, 0, 1]])

In [40]:
np.diag(mat2)

array([1, 1, 1, 2, 2, 1])

In [44]:
mat = np.zeros(16,dtype=int).reshape(4,4)

In [45]:
mat[0,1]=1
mat[2,3]=1
mat[0,2]=1
mat[1,2]=1
mat[0,3]=1

mat[1,0]=1
mat[3,2]=1
mat[2,0]=1
mat[2,1]=1
mat[3,0]=1

In [47]:
np.diag(np.dot(mat,mat))

array([3, 2, 3, 2])